[PARSER]
    Name json
    Format json
    Time_Key time
    Decode_Field_As escaped log

[PARSER]
    Name syslog
    Format regex
    Regex ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
    Time_Key time
    Time_Format %b %d %H:%M:%S

[PARSER]
    Name cpu
    Format regex
    Regex ^(?<time>[^ ]*) (?<cpu_user>[0-9.]+) (?<cpu_system>[0-9.]+) (?<cpu_nice>[0-9.]+) (?<cpu_idle>[0-9.]+) (?<cpu_iowait>[0-9.]+) (?<cpu_irq>[0-9.]+) (?<cpu_softirq>[0-9.]+) (?<cpu_steal>[0-9.]+)$
